// A canonical RF snapshot: 2.4 GHz cell, high utilization + high co-channel
// neighbour count = the RF-24-001 signature. Same shape a vendor adapter emits.
export const EXAMPLE_SNAPSHOT = {
  snapshot_id: 'demo-24-001',
  timestamp: '2026-03-01T12:00:00Z',
  site: { site_id: 'site-042', environment: 'retail' },
  radio: {
    band: '2.4GHz',
    channel: 6,
    channel_width_mhz: 20,
    tx_power_dbm: 12.0,
    tx_power_max_dbm: 23.0,
    admin_state: 'enabled',
  },
  rf_metrics: {
    noise_floor_dbm: -92.0,
    channel_utilization_pct: 77.0,
    rx_utilization_pct: 9.0,
    tx_utilization_pct: 7.0,
    interference_pct: 3.0,
    co_channel_neighbors: 5,
    adjacent_channel_neighbors: 0,
    strongest_neighbor_rssi_dbm: -82.0,
    retry_rate_pct: 7.0,
    crc_error_rate_pct: 1.0,
    airtime_efficiency_pct: 82.0,
  },
  clients: {
    count: 14,
    avg_snr_db: 33.0,
    min_snr_db: 24.0,
    avg_rssi_dbm: -58.0,
    sticky_clients: 0,
    legacy_client_count: 0,
    auth_failures_5m: 0,
    assoc_failures_5m: 0,
    roam_failures_5m: 0,
    avg_roam_time_ms: 55.0,
  },
  capabilities: {
    dot11k: true,
    dot11v: true,
    dot11r: true,
    wpa3_enforced: false,
    band_steering: true,
    min_data_rate_mbps: 12.0,
  },
  analysis_context: {
    observation_window_minutes: 60.0,
    spectrum_capable: false,
    neighbor_scan_available: true,
    client_detail_available: false,
  },
}
